#!/bin/bash
### BEGIN INIT INFO
# Provides:       nodm
# Should-Start:   console-screen kbd hal bluetooth
# Required-Start: $remote_fs
# Required-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:
# Short-Description: No Display Manager / Premine scripts some code from BAMT init.d/gdm / PIMP Modifications by sling00.
### END INIT INFO
#PIMP NODM V1.0.4

#We don't want to fail if a sub process has a non 0 exit code.
#set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="Automatic Display Manager"
NAME=nodm
PIDDIR=/var/run/
PIDFILE=${PIDDIR}/${NAME}.pid

NODM_ENABLED=yes
NODM_XINIT=/usr/bin/xinit
NODM_FIRST_VT=7
NODM_XSESSION=/etc/X11/Xsession
NODM_X_OPTIONS="-nolisten tcp"
NODM_USER=root
NODM_MIN_SESSION_TIME=60
if [ -f /etc/default/$NAME ]
then
	. /etc/default/$NAME
fi

export NODM_XINIT NODM_XSESSION NODM_X_OPTIONS NODM_USER NODM_MIN_SESSION_TIME NODM_FIRST_VT

# If you change the user to a non-root user, make sure you
# set allowed_users=anybody in /etc/X11/Xwrapper.config

# Gracefully exit if the package or its dependencies have been removed (but not purged).
#[ -x /usr/sbin/nodm ] || exit 


# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
. /lib/lsb/init-functions

#Define PiMP Variables
PIMP_NOX=/nox
PIMP_NOXRECONF=/opt/pimp/noxreconf
PIMP_ATICONFIG=/usr/bin/aticonfig
PIMP_XORGCONF=/etc/X11/xorg.conf
PIMP_RM=/bin/rm
#New test defines
ENABLEM="/bin/chmod +x"
DISABLEM="/bin/chmod -x"
MINERS=`cat /opt/ifmi/poolmanager.conf | grep mpath: | sed -n -e 's/^.*mpath: //p'`
#End test defines

case "$1" in
	start)
			log_action_msg "*** PREMINE TASKS STARTING ***"
			log_action_msg "Starting $DESC" "$NAME"
		#New testing code
		if [ -e "/opt/pimp/nomine" ];
		then
			rm /opt/pimp/nomine
			log_warning_msg "PREMINE WARNING: /opt/pimp/nomine was present, your last attempt ati autoconfiguration failed...trying again anyway!"
			$ENABLEM $MINERS
		fi #/tmp/nomine FI #1
		if [ -e "/nomine" ]; then #IF1
			log_warning_msg "PREMINE WARNING: /nomine is present, mining will NOT be started automatically and all miners will be disabled for this session."
			log_warning_msg "Continuing in 5 seconds..."
			sleep 5
			$DISABLEM $MINERS
		fi #FI1
		if [ ! -e "/nomine" ]; then #IF2
	    	log_action_msg "PREMINE INFO: /nomine not present, making sure miners are all enabled"
			$ENABLEM $MINERS
		fi #FI2
		#End testing code

		#Stable code	
		#  IF2 start
 		if [ "$NODM_ENABLED" = "no" ] || [ "$NODM_ENABLED" = "false" ];	
		then log_warning_msg "Not starting $NAME because NODM_ENABLED is '$NODM_ENABLED' in /etc/default/$NAME"
			exit 1
		fi #FI3
		if [ -e $PIMP_NOX ]; #IF4
	    then log_warning_msg "/nox is present, XORG WILL NOT START UNTIL THIS FILE IS REMOVED"
	   						
			exit 1
		fi #FI4
		if [ -e $PIMP_NOXRECONF ]; #IF5
		then	
			log_warning_msg "NOT AUTOMATICALLY CONFIGURING X BECAUSE /opt/pimp/noxreconf is PRESENT!"
			log_warning_msg "IF THIS IS NOT INTENDED rm /opt/pimp/noxreconf"
			log_success_msg "Device list below:"
			$PIMP_ATICONFIG --lsa
		else		
			log_action_msg "Removing Xorg.conf because /opt/pimp/noxreconf does not exist."
			touch $PIMP_XORGCONF
			$PIMP_RM -f $PIMP_XORGCONF 
			log_action_msg "if you need to make manual changes to xorg.conf (NOT RECOMMENDED) use the command:"
			log_action_msg "touch /opt/pimp/noxreconf"
			log_action_msg "Calling aticonfig to create an xorg.conf" 
			if $PIMP_ATICONFIG --adapter=all --initial -f --nobackup 	#IF6	
			then
				log_success_msg "aticonfig was successful, device list below"
#			echo "=================== Detected GPU(s) ==================="
#				
				$PIMP_ATICONFIG --lsa
#				
#				CARDNUM=`$PIMP_ATICONFIG --lsa | grep -c Radeon`
#				if [ -f /root/.gpucount  ];
#					then
#					PREVCOUNT=`cat /root/.gpucount`
#					else
#					PREVCOUNT="0"
#					echo "0" > /root/.gpucount
#				fi
#				if [ $CARDNUM -lt $PREVCOUNT ];
#				    then
#				    echo "======================================================="
#					log_failure_msg  "WARNING: Detected GPU count is LESS than what was detected on previous boot!"
#					log_failure_msg  "Resetting gpu count and setting /opt/ifmi/gpucountbad"
#					echo $CARDNUM > /root/.gpucount
#					touch /opt/ifmi/gpucountbad
#					chown www-data.root /opt/ifmi/gpucountbad
#					chmod 0666 /opt/ifmi/gpucountbad
#					echo 1 > /opt/ifmi/gpucountbad
#					elif [ $CARDNUM -eq $PREVCOUNT ];
#					then
#					echo "======================================================="
#					log_action_msg "New GPU Count is the same as it was before: $CARDNUM"
#					elif [ $CARDNUM -gt $PREVCOUNT ];
#					then
#					GPUDIFF=`echo $CARDNUM - $PREVCOUNT | bc`
#					echo "======================================================="
#					log_action_msg "$CARDNUM Total GPUs Detected..."
#					log_action_msg "$GPUDIFF New GPU(s) Detected...Resetting GPU Count"
#					echo $CARDNUM > /root/.gpucount
#					fi
					echo "======================================================="
				#Test Addition Uncomment to enable and give it a try!
				#aticonfig --acpi-services=off
				#End Test Addition
			else
				log_failure_msg "PREMINE TASKS ERROR *** aticonfig failed - Mining disabled!"
				touch /opt/pimp/nomine
				log_failure_msg "PREMINE TASKS ERROR *** /opt/pimp/nomine is now present due to ati configuration failure, mining will NOT auto-start."
				log_failure_msg "Will try again next boot."
				log_failure_msg "Going failsafe...."
				$DISABLEM $MINERS
				sleep 3	
		fi	#FI6
			log_action_msg "Fixing /root/.Xauthority just incase it was corrupted by an unclean shutdown....."
			touch /root/.Xauthority
			$PIMP_RM /root/.Xauthority 2> /dev/null
		if [ ! -e /etc/X11/xorg.conf ] ; #IF7
		then
			log_action_msg "***FAILSAFE*** trying to generate config with Xorg"#
			if  /usr/bin/Xorg -configure #IF8
			then
				if [ -e /root/xorg.conf.new ] ; #IF9
				then
					log_warning_msg "***FAILSAFE*** Xorg created an xorg.conf"
					mv /root/xorg.conf.new /etc/X11/xorg.conf
	 			elif [ -e /xorg.conf.new ] ;     
            	then
               		log_warning_msg "***FAILSAFE*** Xorg created an xorg.conf"
    	       		mv /xorg.conf.new /etc/X11/xorg.conf     
			else
				log_failure_msg "***CRITICAL*** if Xorg created a config, I cant find it"
			fi #FI9
			else
				log_failure_msg "even Xorg failed to create an X config, bad news"
		fi #FI8
	fi #FI7
		if  [ ! -e "/etc/X11/xorg.conf" ]; #IF10
		then
				log_failure_msg "no xorg.conf, X cannot be started"
				exit 1
		 fi #FI10
	fi #FI5
#premine tasks finished yay! on to the business end.
		log_action_msg "Starting $DESC" "$NAME"

		start-stop-daemon --start --oknodo --pidfile ${PIDFILE} --make-pidfile --background --exec /usr/sbin/nodm
	
		[ "$VERBOSE" != no ] && log_end_msg $?
		;;
	stop)
		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
		start-stop-daemon --stop --pidfile ${PIDFILE} --oknodo
		rm -f ${PIDFILE}
		[ "$VERBOSE" != no ] && log_end_msg $?
		;;
	restart|force-reload)
		$0 stop
		$0 start
		;;
	*)
		log_success_msg "Usage: $0 {start|stop|restart|force-reload}" >&2
		exit 1
		;;
esac


exit 0
